language: objective-c
osx_image: xcode10

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit | xcpretty
- xcodebuild -list -sdk iphonesimulator -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit 
- xcodebuild build test -sdk iphonesimulator -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit CODE_SIGNING_REQUIRED=NO | xcpretty
