language: objective-c
osx_image: xcode10

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild -list -sdk iphonesimulator -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit 
- xcodebuild clean build test -sdk iphonesimulator -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit-Example CODE_SIGNING_REQUIRED=NO | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)