language: objective-c
osx_image: xcode10

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean -workspace Example/VEditorKit.xcworkspace -scheme RxCocoa-Texture | xcpretty
- xcodebuild build -sdk iphonesimulator -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit CODE_SIGNING_REQUIRED=NO | xcpretty
- xcodebuild test -workspace Example/VEditorKit.xcworkspace -scheme VEditorKit -destination 'platform=iOS Simulator,name=iPhone 6,OS=12'