language: objective-c
osx_image: xcode10

xcode_project: Example/VEditorKit.xcodeproj # path to your xcodeproj folder
xcode_scheme: VEditorKit
xcode_destination: platform=iOS Simulator,OS=12,name=iPhone 6

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean -workspace Example/VEditorKit.xcworkspace -scheme RxCocoa-Texture | xcpretty
- xcodebuild build test