language: objective-c
osx_image: xcode10
cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  - git submodule update --init --recursive
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool
  
branches:
  only:
    - master
    
script:
  - rake test:ios